import "../globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  //get all of our pages

  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className=" flex items-center justify-between">
          <Link href="/" className="bg-gradient-to-r from-orange-200 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">
            Mohit
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-400">
            {pages.map((page) => (
              <Link href={`/${page.slug}`} key={page._id} className=" hover:underline">
                {page.title}
              </Link>
            ))}
          </div>
        </header>

        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
